title: Sławosz Kleszcz
url: https://www.drskleszcz.pl
baseurl: ""
timezone: Europe/Oslo
encoding: utf-8
markdown: kramdown
permalink: pretty
form_endpoint: https://formspree.io/f/mnnjbwzp
contact_email: kleszcz.slawosz@gmail.com
collections:
  projects:
    output: true
defaults:
  - scope:
      path: ""
    values:
      layout: default
      lang: en
exclude:
  - _posts
  - .tools
  - .bundle
  - vendor
  - artifacts
  - scripts
  - tests
  - docs
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - freelancer-theme-jekyll.gemspec
  - requirements-dev.txt
  - css
  - js
  - mail
  - style.css
  - feed.xml
  - screenshot.png
social:
  - title: LinkedIn
    url: https://www.linkedin.com/in/slawosz-kleszcz
  - title: GitHub
    url: https://github.com/drSKleszcz/
  - title: ORCID
    url: https://orcid.org/0000-0002-8745-0033
